/* Objects: one entry per thing in the architecture. Extracted from the
   approved arch-explorer-demo.html so the wording survives the rewrite.

   `scale` is required on every object and checked by the schema. See
   ./scale.js for what the two enums mean and why they are not prose. */

import { GROWS, RESILIENCE } from './scale.js';

export const OBJECTS = {
  /* ── Context ── */
  av: { name: "Devcon AV", type: "External actor", icon: "person", external: true,
    tech: ["SRT", "10 to 20 stages"],
    desc: "Produces one program feed per stage on its own network.",
    scale: { count: "20", unit: "one encoder per stage", grows: GROWS.STAGES, resilience: RESILIENCE.EXTERNAL,
      onLoss: "That stage has no picture, and nothing downstream can invent one." },
    blurb: "EF's AV vendor owns capture, vision mix, audio and encoding, on a production network kept separate from the public tier. They have said the video format is adaptable and they will work to whatever specification we give them, so the contribution spec is ours to write.",
    metrics: [["Stages, steady", "10", ""], ["Stages, peak", "20", ""], ["Hours per day", "08:00 to 20:00", ""], ["Contribution", "8 Mbps", ""], ["Venue uplink at 20 stages", "160 Mbps", "open"]],
    note: "The spec to hand them: 1080p30 H.264 High at 8 Mbps CBR, closed GOP, fixed 2 second keyframe interval, no scene-cut keyframes, AAC 128 kbps, and one SRT output per stage to that stage's own address. The keyframe interval is the one people forget, and it is what makes clean segmenting possible. The bitrate is still open: 8 Mbps to feed a 3 Mbps top rung is generous, and 6 would bring 20 stages down to 120 Mbps." },

  sys: { name: "Streaming", type: "Software system", icon: "system", drill: "containers",
    tech: ["swarm-hls-stream"],
    desc: "Ingest, transcode, publish to Swarm. Then get out of the way.",
    scale: { count: "1", unit: "one system, spread across two availability zones", grows: GROWS.FIXED, resilience: RESILIENCE.ZONES,
      onLoss: "Total loss leaves the standby stack as the only thing still carrying viewers, which is exactly why it exists." },
    blurb: "Everything from the encoder output onwards. Receives a produced feed per stage, transcodes a four rung ladder, and writes every segment to Swarm in real time. Viewers then retrieve from Swarm rather than from us: the CDN in front of our per-stage prefetch nodes is how most of them do it and what makes it cheap, but the content is public by address and a viewer holding the reference can fetch it from anywhere. The segments stay behind as the permanent archive.",
    metrics: [["EF's expected peak", "4,000", ""], ["Design ceiling", "40,000", ""], ["Mobile share", "70%", ""], ["Published bitrate", "224 Mbps", ""], ["Event content", "about 2.4 TB", ""]],
    note: "EF asked for stability above everything else. That is why blast radius is contained to one stage, why spare capacity stands ready rather than being hot-paired, and why the standby stack runs from day one." },

  swarm: { name: "Swarm network", type: "External system", icon: "net", external: true,
    tech: ["Bee 2.8", "Gnosis"],
    desc: "Origin, storage, delivery and archive in one.",
    scale: { count: "3,143", unit: "reachable nodes, across 512 neighborhoods at depth 9", grows: GROWS.COVERAGE, resilience: RESILIENCE.EXTERNAL,
      onLoss: "A neighborhood going dark costs roughly one chunk in 512, which erasure coding rebuilds." },
    blurb: "3,143 reachable nodes at the last snapshot. That snapshot put the usable storage radius at 8, giving 256 neighborhoods, and we design coverage for depth 9 and 512 so that a network which has grown since is still covered. Effectively no presence in India, so every Mumbai retrieval crosses to Europe and back.",
    metrics: [["Reachable nodes", "3,143", ""], ["Healthy radius, July survey", "8, so 256 neighborhoods", ""], ["Depth 9", "512, but 14 below four nodes", ""], ["Depth we cover", "9", ""], ["Survey age", "re-run before ordering", "open"], ["Nodes in India", "about zero", ""]],
    note: "A segment's 183 chunks hash into 183 different neighborhoods, which is why no placement trick can steer them and why covering the space evenly is the only thing that works. Blocking one neighborhood blocks a fraction of one chunk in a segment and erasure coding reconstructs it. Censoring the stream means capturing a large fraction of the whole network, not a corner of it. Measure the live depth before the 512 is ordered." },


  viewers: { name: "Viewers", type: "External actor", icon: "person", external: true,
    tech: ["70% mobile"],
    desc: "Global, India-weighted, mostly on phones.",
    scale: { count: "40,000", unit: "the ceiling we build for. EF expects 4,000", grows: GROWS.VIEWERS, resilience: RESILIENCE.CLIENT,
      onLoss: "One person cannot watch. It says nothing about anyone else." },
    blurb: "EF expects a peak around 4,000 concurrent based on previous years. We build to hold 40,000, because the cost of finding the ceiling on the day is the event. Seventy percent are on mobile, which settles two arguments at once: the lower ABR rungs carry most of the audience, and the in-browser node tier can only ever be a desktop footnote.",
    metrics: [["EF's expected peak", "4,000", ""], ["Design ceiling", "40,000", ""], ["Edge sized for", "about 120 Gbps", ""], ["Mobile", "70%", ""], ["Sizing bitrate", "3 Mbps, the top rung", ""], ["Modelled average", "2.2 Mbps", ""]],
    note: "The two bitrates are deliberate and not a contradiction. We size the edge as though every one of the forty thousand took the top rung, because capacity you did not buy is not available on the day. We budget at 2.2 Mbps, because with 70% on mobile and the two lowest rungs at 0.4 and 0.7, nobody will actually average 3. Sizing at the ceiling and costing at the mean is the whole point of having both numbers. iOS Safari uses native HLS, which fetches URLs itself and bypasses any JavaScript loader, so iPhone viewers can never run an in-browser Swarm node no matter how good the client gets." },

  /* ── Containers ── */
  pipeline: { name: "Stage pipeline", type: "Container", icon: "app", drill: "stage",
    tech: ["ffmpeg", "containers"], blast: "1 stage",
    desc: "One isolated worker per stage. Transcode, package, publish.",
    scale: { count: "20", unit: "one worker per stage", grows: GROWS.STAGES, resilience: RESILIENCE.SPARES,
      onLoss: "One stage of twenty, until a standing spare picks it up. The other nineteen never notice." },
    blurb: "Every stage gets its own worker, so a crash takes down exactly one stage. At 20 stages a four rung ladder is roughly 150 vCPU across about 10 machines. Rather than giving each of the 20 workers an idle twin, which would be 40 machines, we run the 20 plus 2 idle spares in a pool: 22 machines instead of 40, and about 30 seconds of black instead of none.",
    metrics: [["Workers at 20 stages", "20", ""], ["vCPU per stage", "about 7", ""], ["Total vCPU", "about 150", ""], ["Idle spares standing by", "2", ""], ["When one dies, what goes dark", "1 stage of 20", ""]],
    note: "Standing spares beat one-to-one hot standby here. A worker is stateless, so a spare has nothing to move across and can be brought up from a clean image, which means paying twice for compute buys a few seconds and nothing else." },


  delivery: { name: "Delivery tier", type: "Container", icon: "system", drill: "deliv",
    tech: ["CDN", "Bee"],
    desc: "Two ways to reach the same bytes. A CDN for most, the network for the rest.",
    scale: { count: "640", unit: "160 prefetch nodes per level, four levels out from the stages", grows: GROWS.COVERAGE, resilience: RESILIENCE.POOL,
      onLoss: "That feed goes cold in one neighborhood. Three other levels still hold it, and the other lane holds the same rung again." },
    blurb: "One kind of node repeated at four distances. Each follows exactly one feed and caches whole segments, so a full copy of the stream is 160 of them. Level 0 sits in the stages' own neighborhoods and feeds the CDN, which is how almost every viewer gets the stream. Levels 1 to 3 sit further out, so a request from an in-browser or external node finishes on one of ours rather than after it. Four levels is what puts a node in all 512 neighborhoods, and one hop is the requirement that sets the number.",
    metrics: [["Peak edge, 40k ceiling", "about 120 Gbps", ""], ["Per level", "160, one per feed", ""], ["Levels", "4", ""], ["Total nodes", "640", ""], ["Unique content", "about 2.4 TB", ""], ["Origin pulls per object", "about 1", ""]],
    note: "Restrict what the CDN serves, never who watches. Swarm content is public by address, so anyone holding the reference can fetch it anywhere. Do not write access control in a document EF reads." },


  player: { name: "Player", type: "Container", icon: "app", drill: "play",
    tech: ["hls.js", "bee-js"],
    desc: "Stock hls.js, one custom loader, and beacons back to us.",
    scale: { count: "40,000", unit: "one per viewer at the ceiling, running on their device", grows: GROWS.VIEWERS, resilience: RESILIENCE.CLIENT,
      onLoss: "One viewer's tab. Our capacity planning never sees it." },
    blurb: "Built on hls.js because its loader is pluggable, which is what lets us fetch segments from Swarm instead of over HTTP. Rung switching is genuinely free: it is stock behaviour off the master playlist and we write nothing for it. Failing over to the standby is not free, and we should not pretend otherwise. What we write is the Swarm loader, the config watcher that performs the switch, and the beacons.",
    metrics: [["Rebuffer SLO", "under 0.5%", ""], ["TTFF target", "under 3 s", ""], ["Latency", "10 to 15 s", ""], ["Rung switching", "stock hls.js", ""], ["Standby switch", "signed config, ours", ""], ["Multi-stage UX", "to build", "open"]],
    note: "On why the standby switch is ours rather than stock: HLS does define redundant streams, and hls.js does implement them, but the reported behaviour is that it exhausts every rung of the primary before trying the backup, and there is no settled way back to primary once it has moved. With a four rung ladder that is four rungs of retries and stalling before a viewer reaches a path that works. So the switch is driven by the signed config feed instead, which reaches every viewer in under 30 seconds and is a decision we make rather than one the library makes for us. Our custom loader also owns the error shape hls.js sees, so the fallback has to be tested against real Swarm failures rather than assumed. The multi-stage viewer experience is separately unbuilt work and it is not small: twenty parallel stages with a schedule, now-playing metadata and a switcher is a real frontend project, and it is the part the audience actually touches." },

  ctrl: { name: "Control plane", type: "Software system", icon: "eye", drill: "control",
    tech: ["Prometheus", "Grafana"],
    desc: "Know what is happening, and be able to act on it.",
    scale: { count: "1", unit: "one control plane for the whole event", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Every stage keeps streaming and we stop being able to see any of it." },
    blurb: "EF asked for stability, which in practice means detection and response rather than more redundancy. Configure the generic parts, Prometheus, Grafana, Loki, Alertmanager and Terraform, then build only what does not exist: the Swarm exporters, the stream prober, the stamp manager and the run-of-show board.",
    metrics: [["Configure", "5 services", ""], ["Build", "4 components", ""], ["Alert channels", "page + chat", ""]],
    note: "Grafana already has accounts, teams, permissions and audit logs. Building a bespoke console would be a three to six month product competing for the same engineers who need to ship ABR over Swarm and the player." },

  netmon: { name: "Network monitor", type: "Software system", icon: "net",
    tech: ["SwarmScan", "bzz-radar"],
    desc: "Watches Swarm itself, separately from watching us.",
    scale: { count: "1", unit: "one watcher on the whole network", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "We keep streaming without knowing whether the ground is moving under us." },
    blurb: "Continuous observation of network size, neighborhood population, reachable node count and anomalies. Deliberately a separate concern from our own health, because it answers a different question: is the ground moving under us.",
    metrics: [["Scope", "whole network", ""], ["Cadence", "15 min", ""], ["Design", "out of scope here", "open"]],
    note: "Partly exists already. SwarmScan publishes a neighborhoods API, and bzz-radar and swarm-staking-stats cover parts of this." },

  /* ── Stage pipeline components ── */
  venueacl: { name: "Venue allowlist", type: "Component", icon: "shield",
    tech: ["firewall"],
    desc: "Only the venue's encoders may reach this stage's port.",
    scale: { count: "20", unit: "one rule set per stage, attached to its address", grows: GROWS.STAGES, resilience: RESILIENCE.DEGRADED,
      onLoss: "The port opens to the internet and the receiver still refuses an unknown streamid. Outer layer gone, inner one holds." },
    blurb: "The stage's port is closed to the internet and open to AV's egress addresses. It is the cheap outer layer: a stranger cannot open a session at all, let alone guess a streamid, and volumetric noise never reaches the worker. It rides on the address rather than the machine, so it follows a stage to its spare.",
    metrics: [["Open to", "venue egress only", ""], ["Public reachability", "none", ""], ["Needs from AV", "their egress IPs", ""]],
    note: "Ask AV for their egress addresses early. It is a five minute answer that takes two weeks to arrive, and without it this ships open on the day." },

  srtin: { name: "SRT receiver", type: "Component", icon: "shield",
    tech: ["srt", "AES"],
    desc: "Terminates SRT and authenticates, on an address that outlives the VM.",
    scale: { count: "20", unit: "one endpoint per stage, on a floating address", grows: GROWS.STAGES, resilience: RESILIENCE.SPARES,
      onLoss: "That stage drops while the address moves to a standing spare, then the encoder reconnects to the same place it always used." },
    blurb: "Each stage listens on its own address, and that address is not the machine's. When a worker dies the address moves to a standing spare and the encoder reconnects to the destination it was configured with months earlier. Nobody at the venue touches anything. Each stage has its own random streamid and passphrase, never stage-1 or stage-2, and an unknown id is refused outright.",
    metrics: [["Auth", "streamid + passphrase", ""], ["Address", "floating, follows the spare", ""], ["Feeds per stage", "1", ""], ["Encoder reconfig", "never", ""], ["Latency buffer", "300 ms", ""]],
    note: "The floating address is what replaced a shared ingest tier. A relay in front would have done the same job and added the one component every stage passes through, and DNS cannot do it at all: SRT resolves once at connect, hardware encoders cache the answer indefinitely, and TTL is advisory." },

  worker: { name: "Transcode worker", type: "Component", icon: "app",
    tech: ["ffmpeg", "x264"], blast: "1 stage",
    desc: "One container per stage. Four rungs out of one feed.",
    scale: { count: "20", unit: "one per stage, plus two idle spares", grows: GROWS.STAGES, resilience: RESILIENCE.SPARES,
      onLoss: "That stage drops while a spare takes over. Stateless, so there is nothing to move across." },
    blurb: "Decodes the 8 Mbps contribution feed and encodes 360p, 480p, 720p and 1080p. The top rung is 3 Mbps, which is what makes a 2 second segment come out at the 750 KB and 183 chunks measured on the stage. Stateless, so it can be killed and restarted freely, which is exactly what makes per-stage isolation affordable.",
    metrics: [["Rungs", "4", ""], ["360p / 480p", "0.4 / 0.7 Mbps", ""], ["720p / 1080p", "1.5 / 3.0 Mbps", ""], ["vCPU", "about 7", ""], ["Blast radius", "1 stage", ""]],
    note: "With 70% of viewers on mobile, the 360p and 480p rungs carry most of the audience. The ladder is not a luxury tier, it is the product for the majority." },

  packager: { name: "HLS packager", type: "Component", icon: "app",
    tech: ["HLS", "2 s"],
    desc: "Segments and playlists, aligned to the keyframes.",
    scale: { count: "20", unit: "one per stage, alongside its worker", grows: GROWS.STAGES, resilience: RESILIENCE.SPARES,
      onLoss: "One stage stops producing segments until the spare is up. The recording still holds those minutes." },
    blurb: "Two second segments cut exactly on the encoder's keyframes, which is why the fixed closed GOP in the contribution spec matters so much. Writes a master playlist plus one variant playlist per rung, then hands the same bytes to both publish lanes. Both lanes uploading identical bytes is what keeps the second lane from doubling what the network stores.",
    metrics: [["Segment", "2 s", ""], ["Variants", "4", ""], ["Fans out to", "8 clients, 2 lanes", ""], ["Window", "live edge", ""]],
    note: "HLS rather than DASH because client support is universal and its segment plus playlist model maps cleanly onto content addressing. Low-latency HLS is deliberately out of scope for a first run, since its partial segments would multiply chunk count and feed update rate." },

  uploader: { name: "Stream uploader A", type: "Component", icon: "app",
    tech: ["swarm-hls-stream"], lane: "A",
    desc: "One per stage. Drives all four rungs into lane A.",
    scale: { count: "20", unit: "one per stage, in this lane", grows: GROWS.STAGES, resilience: RESILIENCE.SINGLE,
      onLoss: "All four rungs stop in this lane for that stage. Lane B carries it and the player never sees it." },
    blurb: "One node process per stage, watching all four rendition outputs and handing each one to its own publisher. It is doing I/O rather than encoding, so four rungs on one process is comfortable. Queued real-time upload with a segment buffer and concurrent uploads. Survives a hard kill and resumes from saved state rather than wrongly finalising the stream to VOD, which is proven by fault injection against a real stack.",
    metrics: [["Uploaders per stage", "1", ""], ["Rungs it drives", "4", ""], ["Buffer", "100 segments", ""], ["Concurrency", "10 uploads", ""], ["Writers per feed", "1, pinned to one host", ""]],
    note: "Two writers on one feed fork it, and there is no distributed lock here to stop that. There does not need to be. A writer is pinned to one host and the supervisor guarantees one process on it, so there is no second place a writer could run from and nothing to coordinate. A frozen process stalls that stage's lane, the supervisor kills and restarts exactly one, and lane B carries the stage meanwhile." },

  uploaderb: { name: "Stream uploader B", type: "Component", icon: "app",
    tech: ["swarm-hls-stream"], lane: "B",
    desc: "The same stage again, on a separate machine.",
    scale: { count: "20", unit: "one per stage, in the second lane", grows: GROWS.STAGES, resilience: RESILIENCE.SINGLE,
      onLoss: "That stage's lane B stops and lane A is unaffected, because the two lanes share no index and no key." },
    blurb: "An identical process reading the same packager output and writing an entirely separate set of feeds. Because the bytes are identical and Swarm is content addressed, the chunks land on the same addresses, so this doubles our egress and our postage but not what the network stores.",
    metrics: [["Uploaders per stage", "1", ""], ["Shares with A", "the packager output", ""], ["Shares with A", "no key, no feed, no index", ""], ["Extra chunks stored", "none", ""]],
    note: "Put lane B on different machines, ideally a different zone. Two lanes on one host buys nothing at all, and that is the easiest way to build this and think you are covered." },

  beepub: { name: "Bee publisher A", type: "Component", icon: "net",
    tech: ["Bee 2.8.1"], lane: "A",
    desc: "One funded, signing node per rung. Four per stage, in lane A.",
    scale: { count: "80", unit: "one per rung per stage, in this lane", grows: GROWS.STAGES, resilience: RESILIENCE.SINGLE,
      onLoss: "That one rung goes quiet in lane A, so viewers on it drop a rung rather than lose the stage." },
    blurb: "Pushes chunks to the neighborhoods that own their addresses and updates the signed feed pointing at that rung's current manifest. One node per rung rather than one per stage, so a full batch or a drained chequebook costs a rung instead of a whole lane. Each holds its own postage batch, keys and chequebook, which makes this the stateful, funded end of the pipeline.",
    metrics: [["Nodes per stage", "4, one per rung", ""], ["Feeds signed", "1 each", ""], ["Postage batch", "1 each", ""], ["Chequebook floor", "0.5 BZZ", ""], ["Key storage", "vault, not the VM", ""]],
    note: "Per-rung nodes buy a second layer of failover on top of one lane B already provides, and the price is 160 chequebooks to fund before the event and 160 balances on the alert board during it. Worth it only because the stamp manager is automating that lifecycle anyway. Whoever holds a signing key controls that rung, so keys live in a vault, never on the VM, and rotate after the event." },

  beepubb: { name: "Bee publisher B", type: "Component", icon: "net",
    tech: ["Bee 2.8.1"], lane: "B",
    desc: "Four more, separate keys, separate postage.",
    scale: { count: "80", unit: "one per rung per stage, in the second lane", grows: GROWS.STAGES, resilience: RESILIENCE.SINGLE,
      onLoss: "That rung goes quiet in lane B and lane A carries it, which is the entire point of running two." },
    blurb: "Independent of lane A in every way that matters: its own Bee nodes, its own signing keys, its own postage batches and its own chequebooks. A full batch, a drained chequebook or a bad build takes out one rung of one lane and leaves everything else publishing.",
    metrics: [["Nodes per stage", "4, one per rung", ""], ["Feeds signed", "1 each", ""], ["Postage batch", "1 each", ""], ["Shares with A", "nothing fundable or signable", ""]],
    note: "This is what makes postage survivable. The measured failure where a full batch kept publishing holes while every log line said success now costs one rung of one lane, and three other rungs plus the whole of lane A are intact." },

  record: { name: "Local recording", type: "Component", icon: "store",
    tech: ["on-site", "post-event"],
    desc: "Post-event only. Nothing in the live path depends on it.",
    scale: { count: "20", unit: "one recorder per stage, at the venue", grows: GROWS.STAGES, resilience: RESILIENCE.DEGRADED,
      onLoss: "Live is unaffected. The archive inherits whatever the network did to that stage." },
    blurb: "One recording per stage, independent of the network path. If contribution drops for ninety seconds the live stream has a gap and nothing changes that, but the permanent archive does not have to inherit it. Everything it is for happens after the event is over.",
    metrics: [["Per stage", "1", ""], ["Used", "after the event", ""], ["Splice owner", "unassigned", "open"], ["In the plan", "not scheduled", "open"]],
    note: "Currently insurance nobody is set up to claim. Splicing means collecting 20 stages times 4 days of files, diffing them against the archive to find the gaps, re-encoding those windows to match the ladder and republishing the manifest. That is an afternoon if there are no gaps and a few days if there are, and it has no owner and no slot in any timeline. Give it both or drop it, but do not call it a safety net while neither is true." },

  /* ── The standby stack, ours ── */
  fallback: { name: "Standby stack", type: "Container", icon: "store", drill: "standby",
    tech: ["object store", "CDN"],
    desc: "Ours, conventional, dormant. The switch if Swarm is not an option.",
    scale: { count: "1", unit: "one standby path for the whole event", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Nothing today. The switch is simply not there on the day we reach for it." },
    blurb: "The same segments written a second time to ordinary object storage behind an ordinary CDN. It runs from day one and serves nobody, because the player only looks at it when the signed config says to. Building our own rather than renting somebody's platform means the fallback fails the way we decided it would rather than the way a vendor decided.",
    metrics: [["State", "hot, unadvertised", ""], ["Switch", "signed config, under 30 s", ""], ["Serves, normally", "nobody", ""]],
    note: "It shares nothing with the Swarm path except the packager output. Different storage, different CDN, different failure modes. A CDN over our own Swarm origin would not have been a fallback at all, because it can only serve what that origin has." },

  objstore: { name: "Segment store", type: "Component", icon: "store",
    tech: ["object storage"],
    desc: "Every segment, written twice, kept plain.",
    scale: { count: "1", unit: "one bucket, every stage, whole event", grows: GROWS.FIXED, resilience: RESILIENCE.EXTERNAL,
      onLoss: "The standby has nothing to serve. Provider-replicated, so this is their failure to have." },
    blurb: "Ordinary object storage holding the same HLS segments and playlists the uploader hands to Swarm. No feeds, no keys, no postage, no signing. A path with nothing clever in it, which is exactly the property a fallback wants.",
    metrics: [["Content", "the same segments", ""], ["Retention", "event + 30 d", ""], ["Clever parts", "none, deliberately", ""]],
    note: "Keep it boring. Every mechanism this shares with the Swarm path is a mechanism that can take both down at once." },

  fallcdn: { name: "Standby CDN", type: "Component", icon: "net",
    tech: ["second provider"],
    desc: "A separate CDN, so one provider cannot take both paths.",
    scale: { count: "1", unit: "one dormant distribution", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "The standby is reachable at origin speed only, which will not carry four thousand viewers." },
    blurb: "A second distribution in front of the segment store, on a different provider from the one fronting the stage prefetch nodes. The failure this exists for includes a CDN having a bad day.",
    metrics: [["Provider", "not the primary", ""], ["State", "configured, no traffic", ""], ["Warm check", "synthetic only", ""]],
    note: "The same provider for both would leave one account, one billing relationship and one status page across both paths, which defeats the point of having two." },

  /* ── Delivery components ── */
  prefetch: { name: "Prefetch nodes", type: "Component", icon: "system",
    tech: ["Bee", "nginx", "depth 9"],
    desc: "One node per feed. A full set of 160 at each level, each level further out.",
    scale: { count: "640", unit: "160 per level, four levels, spread across the address space", grows: GROWS.COVERAGE, resilience: RESILIENCE.POOL,
      onLoss: "That feed goes cold in that one neighborhood. Three other levels still hold it, and the other lane holds the same rung again." },
    blurb: "One kind of node, placed four times over. A node subscribes to exactly one feed, the same way a publisher writes exactly one, so a full copy of the stream is 160 nodes. Level 0 sits in the stages' own neighborhoods and feeds the CDN. Levels 1 to 3 are the same 160 again, ground into neighborhoods further and further out. Each node holds two things at once: every chunk of the feed it follows, wherever those chunks are addressed, and every chunk addressed to its own neighborhood, whichever feed they belong to. That overlap is what makes a request land on one of ours at the end of its route rather than after it.",
    metrics: [["Per level", "160, one per feed", ""], ["Levels", "4", ""], ["Total", "640", ""], ["Per node", "about 1.4 Mbps, about 30 GB", ""], ["Neighborhoods covered", "all 512, at depth 9", ""], ["Worst case for a viewer", "1 hop", ""], ["Machines", "about 80", ""]],
    note: "One hop maximum is the requirement, and it is what sets the level count rather than cost doing it. A retrieval walks toward the chunk's address and finishes in that chunk's neighborhood, so being one hop away means having a node in every neighborhood. Depth 9 is 512 of them and a level is 160 nodes, so four levels is the first count that covers all of them, with 128 doubled up. Ground the addresses deliberately: 640 nodes only cover 512 neighborhoods if they are placed to, and left to chance a random draw leaves about 147 of them empty, since 512 times e to the minus 640 over 512 is how a random scatter lands. On depth 9 rather than 8: the July survey put the healthy storage radius at 8, because depth 9 has 14 neighborhoods holding fewer than four nodes. That is an argument for covering 9 rather than against it, since the thin neighborhoods are exactly where our own node is worth the most, and 512 sections cover the 256 anyway. What the survey cannot tell us is whether those numbers still hold, so re-run it before ordering machines." },


  allow: { name: "Reference allowlist", type: "Component", icon: "shield",
    tech: ["per event"],
    desc: "The follower machines serve our feeds and nothing else.",
    scale: { count: "1", unit: "one list, enforced on every follower machine", grows: GROWS.FIXED, resilience: RESILIENCE.SINGLE,
      onLoss: "The follower machines become a free open proxy for the whole of Swarm, billed to us." },
    blurb: "An allowlist of our feed owners and manifest references. Everything else is refused. This stops the HTTP side being used as a free open proxy for arbitrary Swarm content, which is a genuine cost and abuse problem. It binds the HTTP face only. Every one of these nodes also speaks the Swarm protocol and serves its neighborhood's chunks to the network, exactly as any other node does, and that side is not gated by anything of ours.",
    metrics: [["Scope", "our feeds only", ""], ["Applies to", "the HTTP face, not the Swarm one", ""], ["Write API", "never exposed", ""]],
    note: "This is the achievable half of what people mean by gateway security. The other half, restricting who may watch, is not possible for public content and should not be implied." },

  shield: { name: "Origin shield", type: "Component", icon: "store",
    tech: ["tiered cache"],
    desc: "The setting the whole cost model rests on.",
    scale: { count: "1", unit: "one setting on the CDN, not a box we run", grows: GROWS.FIXED, resilience: RESILIENCE.EXTERNAL,
      onLoss: "Origin pulls jump from about one per object to one per point of presence, and the bill follows." },
    blurb: "With tiered caching the origin serves each unique object roughly once. Without it every point of presence pulls every object independently and origin traffic jumps by an order of magnitude.",
    metrics: [["Origin pulls", "about 1 per object", ""], ["Without shield", "1 per PoP", ""], ["Verify", "during load test", "open"]],
    note: "Verify the shield is actually on and measure origin pull volume during load testing, before anyone quotes a saving that depends on it." },

  cdn: { name: "CDN edge", type: "Component", icon: "net",
    tech: ["volume tier"],
    desc: "Absorbs the viewers, and absorbs the attacks.",
    scale: { count: "many", unit: "rented points of presence, scaled by the provider", grows: GROWS.VIEWERS, resilience: RESILIENCE.EXTERNAL,
      onLoss: "Every viewer lands straight on the 160 level 0 prefetch nodes, and the cost model lands with them." },
    blurb: "Content-addressed segments are immutably cacheable, so the edge gets a near-perfect hit rate and viewer egress becomes cheap. It also doubles as the DDoS absorption layer, which is a service you would otherwise have to build yourself. It answers on our own domain rather than on eth.limo, because eth.limo is volunteer-run and free and pointing 40,000 concurrent viewers at it is a favour nobody agreed to.",
    metrics: [["Peak at EF's 4,000", "about 12 Gbps", ""], ["Peak at the 40,000 ceiling", "about 120 Gbps", ""], ["Front door", "our own domain", ""], ["Also reachable at", "eth.limo, unadvertised", ""], ["Segment TTL", "effectively infinite", ""], ["Manifest TTL", "1 to 2 s", ""]],
    note: "This is a cache, not an origin. Swarm remains origin, storage and archive, and any viewer who distrusts the cache can fetch identical hash-verified bytes from the network directly. No conventional CDN can offer that. Keep eth.limo listed as the censorship-resistant address for anyone who wants it, and carry the load ourselves." },

  browsernode: { name: "In-browser node", type: "External system", icon: "app", external: true,
    tech: ["weeb-3", "WASM"],
    desc: "Somebody else's node, fetching what we published.",
    scale: { count: "unknown", unit: "whoever chooses to run one", grows: GROWS.VIEWERS, resilience: RESILIENCE.EXTERNAL,
      onLoss: "Nothing of ours. They fall back to the same CDN everyone else uses." },
    blurb: "Twenty concurrent viewers, each a real Bee node, watched a live Swarm stream at 2.59% stalled with a 433 ms median retrieval, so it works. It sits outside our system: we run no entry nodes for it, we do not scale for it, and it retrieves from the network the way any other node does. It is the claim being demonstrated rather than a tier we operate.",
    metrics: [["Stalled", "2.59%", ""], ["Retrieval p50", "433 ms", ""], ["Entry nodes we run", "none", ""], ["WSS-reachable mainnet", "unmeasured", "open"]],
    note: "We deliberately do not run wss entry nodes: an unbounded stateful socket serving demand we do not control is not a thing to own for four days. The consequence is that this works only if mainnet already has wss-reachable nodes, and nobody has measured whether it does. Measure before promising it." },

  /* ── Control plane components ── */
  probes: { name: "Synthetic probes", type: "Component", icon: "eye",
    tech: ["4 regions"],
    desc: "Measures what a viewer sees, not what servers think.",
    scale: { count: "4", unit: "one prober per region watched", grows: GROWS.REGIONS, resilience: RESILIENCE.POOL,
      onLoss: "Three regions still report, and one region going quiet is itself a signal worth reading." },
    blurb: "Pull the manifest exactly as a viewer would and assert it is advancing and gapless. Run from Mumbai, Europe, the US and south-east Asia. The most diagnostic probe deliberately fetches uncached content, because if every probe hits cache then everything looks healthy right up until it is not.",
    metrics: [["Manifest liveness", "10 s", ""], ["Segment fetch", "30 s", ""], ["Cold-cache probe", "5 min", ""], ["Regions", "4", ""]],
    note: "This is the highest-value thing in the control plane, because it is the only check that fails when the viewer experience fails rather than when a server does." },

  beacons: { name: "Beacon collector", type: "Component", icon: "eye",
    tech: ["HTTP", "batched"],
    desc: "Receives what the players report. Until now nothing did.",
    scale: { count: "1", unit: "one endpoint, a 5% sample of viewers posts to it", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Every stream keeps playing and we stop learning anything about how it felt to watch." },
    blurb: "The sampled players batch hls.js events and post them here every 30 seconds: rebuffer seconds, startup time, which rung they are on and which path they came down. That becomes Prometheus series and lands on the run-of-show board beside the server-side numbers. Rebuffering is the only one of the four that no server-side log can produce, and it is the one that answers whether the stream was good.",
    metrics: [["Endpoint", "1", ""], ["Reporters at the ceiling", "about 2,000", ""], ["Posts", "batched, every 30 s", ""], ["Third-party trackers", "none", ""], ["Feeds", "metrics and the board", ""]],
    note: "Size it for the worst case rather than the average. A CDN having a bad day makes every player retry and report at once, so this takes its biggest spike exactly when everything else is already on fire. Rate limit it, and never let a failed beacon block playback." },
  metrics: { name: "Metrics", type: "Component", icon: "eye",
    tech: ["Prometheus"],
    desc: "Scrapes every node, stage, gateway and probe.",
    scale: { count: "1", unit: "one scraper for the event", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Every stage keeps streaming and every dashboard goes flat." },
    blurb: "A pull model with one exporter per node keeps collection cheap at this scale. The generic exporters are off the shelf. The one we build is Swarm-specific: chequebook balance, stamp TTL, batch utilisation, pushsync lag, neighborhood population and WSS reachability.",
    metrics: [["Model", "pull", ""], ["Scrape", "15 s", ""], ["Custom exporter", "Swarm", ""]],
    note: "The Swarm exporter is the only genuinely new monitoring code in the whole plan. Everything else is configuration." },

  logs: { name: "Logs", type: "Component", icon: "store",
    tech: ["Loki"],
    desc: "Searchable, labelled by stage, for the post-mortem.",
    scale: { count: "1", unit: "one store, labelled by stage", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Nothing live changes. The post-mortem loses the evidence it was going to be written from." },
    blurb: "Labelled by stage and component so an incident on one stage can be read without wading through nineteen others. Retention covers the event plus the write-up period.",
    metrics: [["Labelled by", "stage, component", ""], ["Retention", "event + 30 d", ""]] },

  alerts: { name: "Alerting", type: "Component", icon: "shield",
    tech: ["Alertmanager"],
    desc: "Pages a human when something needs a human.",
    scale: { count: "1", unit: "one router, tiered by severity", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Everything is still measured and nobody is told, which is the worst of the blind failures." },
    blurb: "Routes by severity. A stage losing its feed pages the on-call. A chequebook nearing its floor tops itself up and only pages if that fails. Alert fatigue over a four day event is a real failure mode, so anything that can self-heal should.",
    metrics: [["Channels", "page + chat", ""], ["On-call", "UTC+5:30 aware", ""], ["Escalation", "tiered", ""]],
    note: "Mumbai is UTC+5:30 and the event runs twelve hours a day for four days. The rota is a real design item and it is still untouched." },

  stamps: { name: "Stamp manager", type: "Component", icon: "store",
    tech: ["postage-batcher"],
    desc: "Buy, top up, dilute, and warn before it hurts.",
    scale: { count: "1", unit: "one manager over 160 batches, one per publisher", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Nothing for hours, then a batch fills and that rung publishes holes while every log line says success. The other seven feeds on that stage are unaffected." },
    blurb: "Postage is the thing that quietly kills a Swarm stream. This owns the whole lifecycle: buy mutable batches, watch TTL and bucket utilisation per batch, dilute before saturation, and top up in bulk atomically. One batch per publisher puts the count at 160, which is only survivable because this component exists to automate it.",
    metrics: [["Batches watched", "160, one per publisher", ""], ["Chequebooks watched", "160", ""], ["Batch type", "mutable", ""], ["Dilute at", "85% utilisation", ""], ["TTL warning", "14 days", ""], ["TTL critical", "7 days", ""]],
    note: "Measured, and it is the reason this component exists: an immutable batch filled 6.5 stream-hours in rather than the 2.3 predicted, and because only the fullest buckets refuse, it kept publishing with holes while every log line said success." },

  cheq: { name: "Chequebook watcher", type: "Component", icon: "store",
    tech: ["on-chain"],
    desc: "Keeps every node funded, or pages someone.",
    scale: { count: "1", unit: "one watcher over every node we run", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Balances drift down until retrieval throttles past the free allowance, quietly and everywhere at once." },
    blurb: "An underfunded chequebook throttles retrieval past the free allowance and degrades delivery quietly. Our own benchmarking found chequebook funding, not segment size, is the single biggest lever on retrieval health.",
    metrics: [["Floor", "0.5 BZZ", ""], ["Action", "auto top-up", ""], ["On failure", "page", ""]],
    note: "Promote this from a preflight test gate to a continuously enforced production invariant. It is the difference between a healthy stream and one that degrades for reasons nobody can see." },

  runofshow: { name: "Run-of-show board", type: "Component", icon: "app",
    tech: ["Grafana"],
    desc: "One row per stage. The thing on the wall.",
    scale: { count: "1", unit: "one board, twenty rows", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "The operators lose the one screen that told them which stage to look at first." },
    blurb: "Twenty rows: stage, scheduled session, feed state, tier, viewers, rebuffer, last segment age. Designed so an operator can see which stage is unhappy without reading a single graph.",
    metrics: [["Rows", "1 per stage", ""], ["Refresh", "10 s", ""], ["Key signal", "last segment age", ""]],
    note: "Last segment age is the most useful number on the board. If it stops climbing the stage is fine, and if it grows past a few segment durations something is wrong regardless of what every other metric says." },

  deploy: { name: "Deploy and rollback", type: "Component", icon: "app",
    tech: ["Terraform", "images"],
    desc: "Add capacity or ship a hotfix, repeatably.",
    scale: { count: "1", unit: "one declarative definition of all of it", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Running capacity is untouched. Adding more becomes a console session under pressure." },
    blurb: "Infrastructure as code so adding gateway or worker capacity is a parameter change rather than a console session. Digest-pinned images so a hotfix is a version bump with a known rollback.",
    metrics: [["Provisioning", "declarative", ""], ["Images", "digest-pinned", ""], ["Rollback", "previous digest", ""]],
    note: "During the event, prefer adding capacity over changing code. A rollback path that has never been exercised is not a rollback path." },

  authz: { name: "Accounts and audit", type: "Component", icon: "shield",
    tech: ["Grafana", "SSO"],
    desc: "Who may do what, and a record of who did.",
    scale: { count: "1", unit: "one directory of people and roles", grows: GROWS.FIXED, resilience: RESILIENCE.DEGRADED,
      onLoss: "Nobody can sign in to change anything, which during an incident is its own kind of outage." },
    blurb: "Accounts, teams and role-based permissions, with every spend-bearing or state-changing action written to an audit log before it runs. Grafana provides most of this already, which is a good reason not to build a console.",
    metrics: [["Model", "role-based", ""], ["Audit", "before the action", ""], ["Spend actions", "flagged", ""]],
    note: "Write the audit entry before the action, not after. An entry records an intent, so it has to survive the attempt failing, otherwise the log only ever tells you about successes." },

  /* ── Player components ── */
  loader: { name: "Swarm loader", type: "Component", icon: "app",
    tech: ["hls.js"],
    desc: "Fetches from feeds, not URLs. The only part of the player that does not exist yet.",
    scale: { count: "40,000", unit: "one per viewer at the ceiling", grows: GROWS.VIEWERS, resilience: RESILIENCE.CLIENT,
      onLoss: "That viewer sees a stall. iPhones never had this one in the first place." },
    blurb: "A custom hls.js loader that resolves the feed, pulls the current manifest and fetches segments by content address. Everything else is stock: hls.js already switches rungs off the master playlist, and HLS already fails a viewer over to a redundant stream, so the standby is listed there rather than picked by anything we wrote. Writing a good ladder is the work, not writing a selector.",
    metrics: [["Source", "our CDN or their own node", ""], ["Rung switching", "stock hls.js", ""], ["Failover", "HLS redundant streams", "open"], ["Manifest merge", "across restarts", ""]],
    note: "Verify hls.js's redundant-stream failover on a bench before relying on it, because that is what replaced a tier selector we would otherwise have built and then had to operate under pressure. Native HLS on iOS Safari bypasses this loader entirely and fetches URLs itself, so iPhone viewers always take the CDN path." },



  telemetry: { name: "Telemetry", type: "Component", icon: "eye",
    tech: ["first-party", "5% sample"],
    desc: "Four numbers, from one viewer in twenty.",
    scale: { count: "2,000", unit: "a 5% sample of viewers at the 40,000 ceiling", grows: GROWS.VIEWERS, resilience: RESILIENCE.CLIENT,
      onLoss: "One session goes unreported. The sample absorbs it without noticing." },
    blurb: "CDN logs already give us concurrency, rung distribution, error rates and geography for free. The one thing they cannot see is rebuffering: the CDN watched a segment leave successfully and has no idea the viewer's buffer ran dry waiting for it. That is the number that says whether the stream was actually good, and it only exists in the player. So we send four numbers, from one viewer in twenty, and nothing else.",
    metrics: [["Sample", "5% of viewers", ""], ["What it sends", "rebuffer, startup, rung, path", ""], ["Cookies and IDs", "none", ""], ["Session key", "random, dies with the tab", ""], ["Post interval", "30 s", ""], ["Code", "about 150 lines on hls.js events", ""]],
    note: "Sampling is what makes this defensible. 2,000 reporters is a solid statistical picture, a trivial load on the collector and a far smaller privacy surface than 40,000. The alternative was CDN logs plus probes and no client code at all, which is legitimate but means the report to EF says we served every request rather than viewers had a good experience. Those are different claims and EF will notice which one we made." }
};
